# Generated by Django 3.2.5 on 2022-11-13 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peptides', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='peptide',
            name='location',
            field=models.IntegerField(default=-1),
        ),
    ]
