# Generated by Django 3.2.5 on 2022-11-13 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peptides', '0002_peptide_location'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='protein',
            index=models.Index(fields=['acc_num'], name='acc_num_idx'),
        ),
    ]
