# Generated by Django 4.1.3 on 2022-11-15 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peptides", "0002_alter_peptide_prot_alter_protein_acc_num"),
    ]

    operations = [
        migrations.AddField(
            model_name="protein",
            name="isoform_num",
            field=models.IntegerField(default=1),
        ),
    ]
