# Generated by Django 4.1.3 on 2022-11-15 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peptides", "0003_protein_isoform_num"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alignment",
            name="prots",
            field=models.CharField(max_length=300, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="peptide",
            name="prot",
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name="protein",
            name="acc_num",
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
